version: "3.9"
services:
    bot:
        build: .
        user: ${UID:-0}
        restart: always
        volumes:
            - ./logs:/code/logs
            - ./settings:/code/settings
            - ./data:/code/data
        env_file:
            - .env
