---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(module)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout


  root_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG 
    formatter: simple
    filename: logs/root.log
    maxBytes: 1048576 # 1MB
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    maxBytes: 1048576 # 1MB
    backupCount: 20
    encoding: utf8


  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR 
    formatter: simple
    filename: logs/error.log
    maxBytes: 1048576 # 1MB
    backupCount: 20
    encoding: utf8

  discord_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG 
    formatter: simple
    filename: logs/discord.log
    maxBytes: 1048576 # 1MB
    backupCount: 20
    encoding: utf8


loggers:
    __main__:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    src.DiscordBot:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no
      
    src.common.Settings:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    src.common.Settings:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    src.logging.logger:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no
        
    src.database.DataBase:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    src.database.DiscordDataBase:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    src.cogs.BaseCog:
          level: DEBUG
          handlers: [console, info_file_handler, error_file_handler]
          propagate: no

    src.cogs.AdminCog:
          level: DEBUG
          handlers: [console, info_file_handler, error_file_handler]
          propagate: no

    src.cogs.ListenerCog:
          level: DEBUG
          handlers: [console, info_file_handler, error_file_handler]
          propagate: no

    src.cogs.AudioCog:
          level: DEBUG
          handlers: [console, info_file_handler, error_file_handler]
          propagate: no


root:
  level: INFO 
  handlers: [root_file_handler, error_file_handler]

